name: Bump version on main pushes

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build distribution
        run: npm run build:prod
      - name: Update version numbers
        run: node scripts/bump-version.mjs
      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No version changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json plugin.json dist/plugin.js
          git commit -m "chore: bump version"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            git push
          else
            echo "Skipping push because no commit was created."
          fi
