name: Ensure plugin uptime

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    name: Check and republish plugin
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Verify published plugin
        id: initial_check
        run: npm run ensure:live
        continue-on-error: true

      - name: Re-release plugin if offline or outdated
        if: steps.initial_check.outcome == 'failure'
        env:
          WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}
        run: |
          echo 'Attempting to re-release plugin because the availability check failed.'
          npm run release

      - name: Re-verify plugin availability
        if: steps.initial_check.outcome == 'failure'
        id: final_check
        run: npm run ensure:live

      - name: Fail workflow if verification never succeeded
        if: steps.initial_check.outcome == 'failure' && steps.final_check.outcome == 'failure'
        run: |
          echo 'Plugin availability check failed even after attempting to re-release.'
          exit 1
