name: Publish Windy Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -f "dist/plugin.js" ]; then
            echo "❌ Build failed: dist/plugin.js not found"
            exit 1
          fi
          echo "✅ Build successful: dist/plugin.js created"
          ls -la dist/

      - name: Test packaging
        run: npm run package

      - name: Verify package
        run: |
          if [ ! -f "windy-plugin-heat-units.tar" ]; then
            echo "❌ Packaging failed: windy-plugin-heat-units.tar not found"
            exit 1
          fi
          echo "✅ Package created successfully"
          tar -tf windy-plugin-heat-units.tar | head -10

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check API key
        env:
          WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}
        run: |
          if [ -z "$WINDY_API_KEY" ]; then
            echo "❌ Error: WINDY_API_KEY secret is not set"
            echo "Please add your Windy API key to repository secrets"
            exit 1
          fi
          echo "✅ API key is configured"

      - name: Publish to Windy
        env:
          WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}
        run: npm run release

      - name: Upload build artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            dist/
            *.tar
            package.json
            plugin.json
