name: Publish Windy plugin

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Upload archive to the Windy CDN
        required: true
        type: boolean
        default: true

permissions:
  contents: read

env:
  WINDY_PUBLISH: ${{ inputs.publish && 'true' || 'false' }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      WINDY_PUBLISH: ${{ inputs.publish && 'true' || 'false' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build archive (and optionally publish)
        id: release
        env:
          WINDY_API_KEY: ${{ secrets.WINDY_API_KEY }}
        run: |
          if [ "$WINDY_PUBLISH" != "true" ]; then
            export WINDY_DRY_RUN=1
            echo "Running in dry-run mode – the archive will not be uploaded."
          else
            if [ -z "$WINDY_API_KEY" ]; then
              echo "Missing WINDY_API_KEY secret." >&2
              exit 1
            fi
          fi
          npm run release

      - name: Upload plugin archive artifact
        if: success() && hashFiles('windy-plugin-heat-units.tar') != ''
        uses: actions/upload-artifact@v4
        with:
          name: windy-plugin-heat-units.tar
          path: windy-plugin-heat-units.tar
          if-no-files-found: error

      - name: Publish workflow summary
        if: success()
        env:
          WINDY_PUBLISH: ${{ inputs.publish && 'true' || 'false' }}
        run: |
          node --input-type=module <<'NODE'
          import { appendFile } from 'node:fs/promises';
          import { readFileSync } from 'node:fs';

          const plugin = JSON.parse(readFileSync('plugin.json', 'utf8'));
          const name = plugin.name ?? 'unknown';
          const version = plugin.version ?? 'unknown';
          const publish = process.env.WINDY_PUBLISH === 'true';

          const lines = [
            '## Windy plugin release',
            '',
            `- **Plugin**: ${name}`,
            `- **Version**: ${version}`,
            `- **CDN URL template**: https://windy-plugins.com/<your-user-id>/${name}/${version}/plugin.min.js`,
            publish
              ? '- The workflow uploaded the archive to Windy.'
              : '- Dry run: the archive was generated but not uploaded.',
            '',
          ];

          const output = lines.join('\n');
          console.log(output);

          if (process.env.GITHUB_STEP_SUMMARY) {
            await appendFile(process.env.GITHUB_STEP_SUMMARY, output + '\n');
          }
          NODE
