name: Publish Windy Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Create plugin archive
        run: tar cf plugin.tar --exclude='./plugin.tar' --exclude='.git' --exclude='node_modules' .

      - name: Publish to Windy
        if: github.ref == 'refs/heads/main'
        run: |
          curl -XPOST 'https://www.windy-plugins.com/plugins/v1.0/upload' \
            -H "x-windy-api-key: ${{ secrets.WINDY_API_KEY }}" \
            -F "plugin_archive=@./plugin.tar"
